//! ORM for PostgreSQL based on SQL migration scripts.
pub mod migration;

/// Include models that was generated by [porm-parser](https://crates.io/crates/porm-parser).
///
/// This will pull generated models into the calling module. This also pull migration list to be
/// used with [migrate](crate::migration::migrate()).
///
/// Environment variable `PORM_GENERATED_FILE` must be set to the generated file.
pub use porm_macros::include_models;
